### ISSUE TITLE
npm install is failing with the following message

### ISSUE THREAD

**Issue by briviere** [dvdcastro/keystonejs-ng-skeleton#4]
1331 verbose stack Error: v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
1331 verbose stack Exit status 1
1331 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
1331 verbose stack     at emitTwo (events.js:87:13)
1331 verbose stack     at EventEmitter.emit (events.js:172:7)
1331 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
1331 verbose stack     at emitTwo (events.js:87:13)
1331 verbose stack     at ChildProcess.emit (events.js:172:7)
1331 verbose stack     at maybeClose (internal/child_process.js:818:16)
1331 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
1332 verbose pkgid v8-debug@0.4.6
1333 verbose cwd /home/brian/keystonejs-ng-skeleton
1334 error Linux 3.13.0-37-generic
1335 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
1336 error node v4.2.1
1337 error npm  v3.3.9
1338 error code ELIFECYCLE
1339 error v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
1339 error Exit status 1
1340 error Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
1340 error This is most likely a problem with the v8-debug package,
1340 error not with npm itself.
1340 error Tell the author that this fails on your system:
1340 error     node-pre-gyp install --fallback-to-build
1340 error You can get their info via:
1340 error     npm owner ls v8-debug
1340 error There is likely additional logging output above.
1341 verbose exit [ 1, true ]

**Comment by briviere** [comment]
going into <app>/node_modules/mongodb and running npm install resolved this issue.

brian
